services:
  _defaults:
    public: true

  # Fixtures/Seeders
  App\DataFixtures\AppFixtures:
    arguments:
      - '@doctrine.dbal.default_connection'

  # Mappers
  hotelplex.mapper.hotel:
    class: HotelPlex\Infrastructure\Mapper\Hotel\AutoMapperPlusHotelMapper

  # Repositories
  hotelplex.repository.hotel:
    class: HotelPlex\Infrastructure\Repository\Hotel\DoctrineHotelRepository
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@hotelplex.mapper.hotel'

  # Resolvers
  App\GraphQL\Resolver\HotelResolver:
    arguments:
      - '@service_container'

  App\GraphQL\Resolver\HotelsResolver:
    arguments:
      - '@service_container'
