version: '3.7'

services:
    mysql:
      container_name: hotelplex-mysql
      image: mysql:5.7
      volumes:
        - "./var/mysql:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
      env_file:
          - .env
      ports:
        - "3330:3306"

    php:
      build: .
      container_name: hotelplex-php
      volumes:
        - .:/application
      depends_on:
        - mysql

    webserver:
      image: nginx:alpine
      container_name: hoteplex-webserver
      volumes:
        - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8888:80"
      depends_on:
        - php
