token_post_controller:
  path: /auth/token
  methods: [POST]
  controller: App\Controller\Auth\TokenPostController

user_post_controller:
  path: /users
  methods: [POST]
  controller: App\Controller\User\RegisterUserPostController

payment_list_get_controller:
  path: /payments
  methods: [GET]
  controller: App\Controller\Payment\PaymentListGetController
