services:
  _defaults:
    public: true

  # Auth

  App\GraphQL\Auth\TokenResolver:
    arguments:
      - '@service_container'

  # Hotel

  App\GraphQL\Hotel\HotelResolver:
    arguments:
      - '@service_container'

  App\GraphQL\Hotel\HotelsResolver:
    arguments:
      - '@service_container'

  # Provider

  App\GraphQL\Provider\RegisterProviderResolver:
    arguments:
    - '@service_container'

  # Payment

  App\GraphQL\Payment\PaymentInfoResolver:
    arguments:
    - '@service_container'
