services:
  _defaults:
    public: true

  hotelplex.mapper.hotel:
    class: HotelPlex\Infrastructure\Mapper\Hotel\AutoMapperPlusHotelMapper

  hotelplex.mapper.payment:
    class: HotelPlex\Infrastructure\Mapper\Payment\AutoMapperPlusPaymentMapper

  hotelplex.mapper.user:
    class: HotelPlex\Infrastructure\Mapper\User\AutoMapperPlusUserMapper

  hotelplex.mapper.provider:
    class: HotelPlex\Infrastructure\Mapper\Provider\AutoMapperPlusProviderMapper
