Payment:
  type: object
  config:
    fields:
      uuid:
        type: 'String!'
      method:
        type: 'String!'
      currency:
        type: 'String!'
      price:
        type: 'Float!'
      createdAt:
        type: 'String!'
