Query:
  type: object
  config:
    fields:
      token:
        type: "String!"
        args:
          email:
            type: "String!"
          password:
            type: "String!"
        resolve: '@=resolver("App\\GraphQL\\Auth\\TokenResolver", [args])'
      hotel:
        type: "Hotel!"
        args:
          uuid:
            type: "String!"
        resolve: '@=resolver("App\\GraphQL\\Hotel\\HotelResolver", [args])'
      hotelList:
        type: "[Hotel!]!"
        resolve: '@=resolver("App\\GraphQL\\Hotel\\HotelListResolver", [args])'
      paymentList:
        type: "[Payment!]!"
        resolve: '@=resolver("App\\GraphQL\\Payment\\PaymentListResolver", [args])'
      paymentInfo:
        type: "[Payment!]!"
        args:
          uuid:
            type: "String!"
        resolve: '@=resolver("App\\GraphQL\\Payment\\PaymentInfoResolver", [args])'
