Query:
  type: object
  config:
    fields:
      token:
        type: "String!"
        args:
          email:
            type: "String!"
          password:
            type: "String!"
        resolve: '@=resolver("App\\GraphQL\\Auth\\TokenResolver", [args])'
      hotelInfo:
        type: "Hotel!"
        args:
          uuid:
            type: "String!"
        resolve: '@=resolver("App\\GraphQL\\Hotel\\HotelResolver", [args])'
      hotelsInfo:
        type: "[Hotel!]!"
        resolve: '@=resolver("App\\GraphQL\\Hotel\\HotelsResolver", [args])'
