Query:
  type: object
  config:
    fields:
      token:
        type: "String!"
        args:
          email:
            type: "String!"
          password:
            type: "String!"
        resolve: "@=resolver('TokenResolver', [args])"
      hotelInfo:
        type: "Hotel!"
        args:
          uuid:
            type: "String!"
        resolve: "@=resolver('HotelResolver', [args])"
      hotelsInfo:
        type: "[Hotel!]!"
        resolve: "@=resolver('HotelsResolver', [args])"
