# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

imports:
    # HotelPlex
    - { resource: ../src/HotelPlex/Infrastructure/Mapper/services.yaml }
    - { resource: ../src/HotelPlex/Infrastructure/Presenter/services.yaml }
    - { resource: ../src/HotelPlex/Infrastructure/Repository/services.yaml }
    # AppBundle
    - { resource: ../src/AppBundle/DataFixtures/services.yaml }
    - { resource: ../src/AppBundle/GraphQL/services.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/AppBundle/*'
        exclude: '../src/AppBundle/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    App\Listener\:
        resource: '../src/AppBundle/Listener'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
